Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /send-magic-link/
"POST /send-magic-link/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Forbidden (CSRF cookie not set.): /login1/
"POST /login1/ HTTP/1.1" 403 2855
Too Many Requests: /login1/
"POST /login1/ HTTP/1.1" 429 64
Too Many Requests: /login1/
"POST /login1/ HTTP/1.1" 429 64
Too Many Requests: /login1/
"POST /login1/ HTTP/1.1" 429 64
Too Many Requests: /login1/
"POST /login1/ HTTP/1.1" 429 64
Internal Server Error: /signup1/
Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 57, in _get_backend_from_user
    backend = backend or user.backend
                         ^^^^^^^^^^^^
AttributeError: 'CustomUser' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\.fida\Fida\pyprojects\FUR_PDF\fur_pdf_app\fur_pdf_editor\views.py", line 51, in signup_view
    login(request, user)
    ~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 189, in login
    backend = _get_backend_from_user(user=user, backend=backend)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 63, in _get_backend_from_user
    raise ValueError(
    ...<3 lines>...
    )
ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.
"POST /signup1/ HTTP/1.1" 500 89296
Internal Server Error: /upload/
Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\.fida\Fida\pyprojects\FUR_PDF\fur_pdf_app\fur_pdf_editor\views.py", line 79, in upload_pdf
    return render(request, 'upload_pdf.html', {'form': form})
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 590, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 2: 'block'. Looking for one of: endblock.
"GET /upload/ HTTP/1.1" 500 166837
Too Many Requests: /account/login/
"POST /account/login/?next=/list/ HTTP/1.1" 429 64
Forbidden (CSRF token from POST incorrect.): /login1/
"POST /login1/ HTTP/1.1" 403 2503
"GET /static/images/team_member_1.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_2.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_4.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_3.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_1.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_2.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_4.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_3.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_2.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_1.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_3.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_4.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_1.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_2.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_3.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_4.jpg HTTP/1.1" 404 1890
"GET /static/media/default_profile_male.png HTTP/1.1" 404 1908
"GET /static/images/team_member_2.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_3.jpg HTTP/1.1" 404 1890
"GET /static/images/team_member_4.jpg HTTP/1.1" 404 1890
"GET /static/media/default_profile_male.png HTTP/1.1" 404 1908
"GET /static/media/ HTTP/1.1" 404 1836
Internal Server Error: /about/
Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\.fida\Fida\pyprojects\FUR_PDF\fur_pdf_app\fur_pdf_editor\views.py", line 64, in about
    return render(request, 'about.html')
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 68: 'media', expected 'endblock'. Did you forget to register or load this tag?
"GET /about/ HTTP/1.1" 500 191778
Internal Server Error: /about/
Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\.fida\Fida\pyprojects\FUR_PDF\fur_pdf_app\fur_pdf_editor\views.py", line 64, in about
    return render(request, 'about.html')
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'media' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
django_bootstrap5
i18n
l10n
log
rest_framework
static
two_factor_tags
tz
"GET /about/ HTTP/1.1" 500 200470
Internal Server Error: /about/
Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\.fida\Fida\pyprojects\FUR_PDF\fur_pdf_app\fur_pdf_editor\views.py", line 64, in about
    return render(request, 'about.html')
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "d:\.fida\Fida\pyprojects\FUR_PDF\.venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'media' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
django_bootstrap5
i18n
l10n
log
rest_framework
static
two_factor_tags
tz
"GET /about/ HTTP/1.1" 500 200351
